export const summerCourseLessons = [
  {
    "id": "summer-waicy-xuhui-sophie-2026-06-29-1530",
    "teacherId": "sophie",
    "teacherName": "Sophie",
    "studentName": "Ivan,小米",
    "course": "WAICY 徐汇集训班",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-06-29",
    "startTime": "15:30",
    "endTime": "18:30",
    "status": "已确认",
    "notes": "正常上课 1、3、4上课",
    "source": "暑假课程排课系统.xlsx/课程表!A4"
  },
  {
    "id": "summer-waicy-xuhui-sophie-2026-07-01-1530",
    "teacherId": "sophie",
    "teacherName": "Sophie",
    "studentName": "Ivan,小米",
    "course": "WAICY 徐汇集训班",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-01",
    "startTime": "15:30",
    "endTime": "18:30",
    "status": "已确认",
    "notes": "正常上课 1、3、4上课",
    "source": "暑假课程排课系统.xlsx/课程表!A4"
  },
  {
    "id": "summer-waicy-xuhui-sophie-2026-07-02-1530",
    "teacherId": "sophie",
    "teacherName": "Sophie",
    "studentName": "Ivan,小米",
    "course": "WAICY 徐汇集训班",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-02",
    "startTime": "15:30",
    "endTime": "18:30",
    "status": "已确认",
    "notes": "正常上课 1、3、4上课",
    "source": "暑假课程排课系统.xlsx/课程表!A4"
  },
  {
    "id": "summer-waicy-xuhui-sophie-2026-07-06-1530",
    "teacherId": "sophie",
    "teacherName": "Sophie",
    "studentName": "Ivan,小米",
    "course": "WAICY 徐汇集训班",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-06",
    "startTime": "15:30",
    "endTime": "18:30",
    "status": "已确认",
    "notes": "正常上课 1、3、4上课",
    "source": "暑假课程排课系统.xlsx/课程表!A4"
  },
  {
    "id": "summer-finance-xuhui-phebe-2026-07-07-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 徐汇暑期课",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-07",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A2"
  },
  {
    "id": "summer-finance-xuhui-phebe-2026-07-08-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 徐汇暑期课",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-08",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A2"
  },
  {
    "id": "summer-waicy-xuhui-sophie-2026-07-08-1530",
    "teacherId": "sophie",
    "teacherName": "Sophie",
    "studentName": "Ivan,小米",
    "course": "WAICY 徐汇集训班",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-08",
    "startTime": "15:30",
    "endTime": "18:30",
    "status": "已确认",
    "notes": "正常上课 1、3、4上课",
    "source": "暑假课程排课系统.xlsx/课程表!A4"
  },
  {
    "id": "summer-finance-xuhui-phebe-2026-07-09-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 徐汇暑期课",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-09",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A2"
  },
  {
    "id": "summer-waicy-xuhui-sophie-2026-07-09-1530",
    "teacherId": "sophie",
    "teacherName": "Sophie",
    "studentName": "Ivan,小米",
    "course": "WAICY 徐汇集训班",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-09",
    "startTime": "15:30",
    "endTime": "18:30",
    "status": "已确认",
    "notes": "正常上课 1、3、4上课",
    "source": "暑假课程排课系统.xlsx/课程表!A4"
  },
  {
    "id": "summer-finance-xuhui-phebe-2026-07-10-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 徐汇暑期课",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-10",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A2"
  },
  {
    "id": "summer-waicy-xuhui-sophie-2026-07-13-1530",
    "teacherId": "sophie",
    "teacherName": "Sophie",
    "studentName": "Ivan,小米",
    "course": "WAICY 徐汇集训班",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-13",
    "startTime": "15:30",
    "endTime": "18:30",
    "status": "已确认",
    "notes": "正常上课 1、3、4上课",
    "source": "暑假课程排课系统.xlsx/课程表!A4"
  },
  {
    "id": "summer-finance-xuhui-phebe-2026-07-14-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 徐汇暑期课",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-14",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A2"
  },
  {
    "id": "summer-finance-xuhui-phebe-2026-07-15-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 徐汇暑期课",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-15",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A2"
  },
  {
    "id": "summer-waicy-xuhui-sophie-2026-07-15-1530",
    "teacherId": "sophie",
    "teacherName": "Sophie",
    "studentName": "Ivan,小米",
    "course": "WAICY 徐汇集训班",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-15",
    "startTime": "15:30",
    "endTime": "18:30",
    "status": "已确认",
    "notes": "正常上课 1、3、4上课",
    "source": "暑假课程排课系统.xlsx/课程表!A4"
  },
  {
    "id": "summer-finance-xuhui-phebe-2026-07-16-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 徐汇暑期课",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-16",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A2"
  },
  {
    "id": "summer-finance-xuhui-phebe-2026-07-17-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 徐汇暑期课",
    "deliveryType": "线下",
    "campus": "徐汇",
    "location": "上海电影厂 1108",
    "date": "2026-07-17",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A2"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-07-21-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-07-21",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A3"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-07-22-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-07-22",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A3"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-07-23-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-07-23",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A3"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-07-24-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-07-24",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A3"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-07-28-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-07-28",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A3"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-07-29-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-07-29",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A3"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-07-30-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-07-30",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A3"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-07-31-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-07-31",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A3"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-08-04-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-08-04",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A5"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-08-05-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-08-05",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A5"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-08-06-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-08-06",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A5"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-08-07-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-08-07",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A5"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-08-11-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-08-11",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A5"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-08-12-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-08-12",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A5"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-08-13-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-08-13",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A5"
  },
  {
    "id": "summer-finance-pudong-phebe-2026-08-14-1515",
    "teacherId": "phebe",
    "teacherName": "Phebe",
    "studentName": "班课",
    "course": "财商x樱桃 浦东暑期课",
    "deliveryType": "线下",
    "campus": "浦东",
    "location": "樱桃图书馆",
    "date": "2026-08-14",
    "startTime": "15:15",
    "endTime": "16:15",
    "status": "待确认",
    "notes": "需要名单 8天",
    "source": "暑假课程排课系统.xlsx/课程表!A5"
  }
];
